name: Download & Unzip sing-box.zip

on:
  workflow_dispatch:   # 手动执行工作流
  push:                 # 每次推送时自动执行
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download sing-box.zip
        run: |
          wget -O sing-box.zip https://github.com/gumingxin/sing-box-subscribe/raw/refs/heads/main/sing-box.zip

      - name: Unzip file to repo root
        run: |
          unzip -o sing-box.zip -d .
          rm sing-box.zip

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update sing-box files" || echo "No changes"
          git push
